---
fixtures:
  repositories:
    augeasproviders_core: https://github.com/simp/augeasproviders_core
    augeasproviders:ssh: https://github.com/simp/augeasproviders_ssh
    logrotate: https://github.com/simp/pupmod-simp-logrotate
    rsyslog: https://github.com/simp/pupmod-simp-rsyslog
    simplib: https://github.com/simp/pupmod-simp-simplib
    ssh: https://github.com/simp/pupmod-simp-ssh
    stdlib: https://github.com/simp/puppetlabs-stdlib
    systemd: https://github.com/simp/puppet-systemd
  symlinks:
    tlog: "#{source_dir}"
